### ISSUE TITLE
compilation failed with openjdk-9

### ISSUE THREAD

**Issue by sektorcap** [spinscale/cookiecutter-elasticsearch-ingest-processor#6]
A simple test plugin fails to compile with openjdk-9 on Ubuntu 16.04.
Following the error.

```
$ gradle clean check

> Configure project : 
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.5.1
  OS Info               : Linux 4.13.0-36-generic (amd64)
  JDK Version           : Oracle Corporation 9-internal [OpenJDK 64-Bit Server VM 9-internal+0-2016-04-14-195246.buildd.src]
  JAVA_HOME             : /usr/lib/jvm/java-9-openjdk-amd64
  Random Testing Seed   : 458957941FC90A4E

> Task :compileJava FAILED
javac: invalid flag: --release
Usage: javac <options> <source files>
use -help for a list of possible options
javac: no source files
Usage: javac <options> <source files>
use -help for a list of possible options


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed with exit code 2; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
2 actionable tasks: 2 executed
```

Any idea?
Thanks in advance

**Comment by sektorcap** [comment]
Seems to be an openjdk-9 problem. With Oracle Java 9 everything works fine.
```
$ gradle clean check

> Configure project : 
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.5.1
  OS Info               : Linux 4.13.0-36-generic (amd64)
  JDK Version           : Oracle Corporation 9.0.4 [Java HotSpot(TM) 64-Bit Server VM 9.0.4+11]
  JAVA_HOME             : /usr/lib/jvm/java-9-oracle
  Random Testing Seed   : 5346968FF81FAF75

> Task :jar 
Building without git revision id.

> Task :test 
==> Test Info: seed=AEAF61557070F574; jvm=1; suite=1
==> Test Summary: 1 suite, 1 test

> Task :integTestRunner 
==> Test Info: seed=8B2C0CA643B4FB76; jvm=1; suite=1
==> Test Summary: 1 suite, 2 tests


Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 20s
32 actionable tasks: 31 executed, 1 up-to-date
```

**Comment by spinscale** [comment]
judging from the openjdk9 versions, that ubuntu build seems older than the release date, so I assume it is not post release.

Closing this one.
